site_name: Pipeline Documentation
site_url: https://github.com/ramsainanduri/pipeline_documentation
github_url: https://github.com/ramsainanduri/pipeline_documentation
nav:
- Home: index.md
- Introduction: Introduction.md
- Scope: Scope.md
- Min_requirements: Min_requirements.md
- Usage: Usage.md
- Pipeline Components: Pipeline Components.md
- Profiles:
  - Myeloid: profiles/Myeloid.md
  - Solid: profiles/Solid.md
- Workflow Diagram: Workflow Diagram.md
theme:
  name: readthedocs
  logo: https://raw.githubusercontent.com/ramsainanduri/pipeline_documentation/dev/templates/rs-logo-color.svg
  highlightjs: true
  hljs_languages:
  - yaml
  - rust
plugins:
- search:
    indexing: full
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: sphinx
markdown_extensions:
- abbr
- attr_list
- pymdownx.details
- toc:
    permalink: true
- markdown_include.include:
    base_path: .
- admonition
extra:
  generator: false
extra_css:
- extra.css
copyright: "Copyright &copy; 2023 | Center for Molecular Diagnostics (CMD) | Region\
  \ Sk\xE5ne | S\xF6lvegatan 23B, Lund."
