---
title: '`r params$pipeline$name`'
output: 
  rmdformats::readthedown:
    toc_depth: 2
    toc_float: true
    theme: united
    highlight: tango
    fig_width: 7
    fig_height: 6
    fig_caption: true
    keep_md: true
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: false
    url: blue

date: '`r Sys.Date()`'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(rmarkdown)
library(kableExtra)
library(DT)
library(dplyr)
```

# Pipeline Details

**Name:** `r params$pipeline$name`

**Version:** `r params$pipeline$version`

**Contact Person:** `r params$pipeline$contact_person`

**Location:** `r params$pipeline$location`

# Description

`r params$pipeline$description`

# Minimum Requirements

**Nextflow version:** `r params$pipeline$min_requirements$nextflow_version`

# List of Software Used

```{r, echo=FALSE,warning=FALSE, message=FALSE, results='asis'}
software_list = read.table(file = params$pipeline$software_list, sep = '\t', header = TRUE, stringsAsFactors = FALSE, check.names=F)
software_list =  software_list[order(software_list$`Tool/Software`),]
software_list$ID <- seq.int(nrow(software_list))
software_list <- software_list %>% select(ID, everything())
software_list$`Tool/Software` = paste('<a href = "',software_list$URL,'" target="_blank">',software_list$`Tool/Software`,'</a>',sep='')
software_list$Reference = paste('<a href = "',software_list$Reference,'" target="_blank">open</a>',sep='')
software_list = select(software_list, -c(URL,'Short Description'))
#datatable(software_list,caption = 'Table 1: List of software/Tools used.', rownames = FALSE, escape=FALSE, class = 'cell-border compact stripe hover', options = list(columnDefs = list(list(className = 'dt-center', targets = "_all")), pageLength = 5, scroller=T, dom = 'Blfrtip', lengthMenu = list(c(5,10,15,25,50,-1), c(5,10,15,25,50,"All"))))
kable(software_list,booktabs=TRUE,  escape=FALSE,row.names=FALSE) %>%
  kable_styling(bootstrap_options = c("striped", "hover",  "condensed", "responsive"),full_width = F, position = "center")
```
